version: '3.4'

services:
  restaurantreservationapp.api:
    image: ${DOCKER_REGISTRY-}restaurantreservationappapi
    build:
      context: .
      dockerfile: RestaurantReservationApp.API/Dockerfile
    ports:
      - "6000:6000"
      - "6001:6001" 
    depends_on:
      - restaurantreservationapp.database
    networks:
      - mynetwork
  restaurantreservationapp.database:
    image: postgres:latest
    container_name: restaurantreservationapp.database
    environment:
      - POSTGRES_DB=RestaurantReservation
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 54320:5432
    networks:
      - mynetwork

volumes:
  postgres_data:
    driver: local
networks:
  mynetwork: